name: linters
on: push
jobs:
  standardrb:
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 3.1
          - 3.2
          - 3.3
          - 3.4

    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run standardrb
        run: bundle exec standardrb
