name: Publish
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Setup GitHub Package Registry credentials
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:github: Bearer ${{ secrets.GITHUB_TOKEN }}\n" > $HOME/.gem/credentials

      - name: Replace version by tag value
        run: sed -i "s/\"[0-9]\.[0-9]\..*\"/\"${GITHUB_REF##*/}\"/" lib/appsignal/sourcemap/version.rb

      - name: Build and Publish gem to GitHub Package Registry
        run: |
          gem build --verbose *.gemspec
          gem push --verbose --key github --host https://rubygems.pkg.github.com/${OWNER} *.gem
        env:
          OWNER: Drieam
